version: '3'

services:
  php-web0:
    image: akitokageyama/php56
    container_name: php-web0
    working_dir: /var/www
    ports:
      - 10100:80
    links:
      - mysql0
    volumes:
      - "./root:/var/www"
      - "./docker/php-web/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-web/custom-vhost.conf:/etc/apache2/sites-available/000-default.conf"

  mysql0:
    image: library/mysql:5.7
    container_name: mysql0
    ports:
      - 13400:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin0:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql0
      - PMA_USER=test
      - PMA_PASSWORD=test
    links:
      - mysql0
    ports:
      - 14100:80
    volumes:
      - "./docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./docker/phpmyadmin/sessions:/sessions"
